const clientSeeds = [
    {
        code: '70',
        name: 'PT BIMASAKTI MULTI ENERGi',
        type_trans: 'Cash Withdrawal',
        acq_fee_atmi: 250,
        acq_fee_ads: 150,
        acq_fee_client: 2000,
        switching_fee_alto: 950,
        recon_fee_alto: 2750,
        beneficiary: 0,
        acq_fee_rts: 150,
        acq_fee_ndp: 1250
    },
    {
        code: '70',
        name: 'PT BIMASAKTI MULTI ENERGi',
        type_trans: 'Funds Transfer',
        acq_fee_atmi: 250,
        acq_fee_ads: 150,
        acq_fee_client: 1000,
        switching_fee_alto: 1200,
        recon_fee_alto: 900,
        beneficiary: 1500,
        acq_fee_rts: 250,
        acq_fee_ndp: 1250
    },
    {
        code: '70',
        name: 'PT BIMASAKTI MULTI ENERGi',
        type_trans: 'Balance Inquiry',
        acq_fee_atmi: 200,
        acq_fee_ads: 150,
        acq_fee_client: 1000,
        switching_fee_alto: 750,
        recon_fee_alto: 750,
        beneficiary: 0,
        acq_fee_rts: 250,
        acq_fee_ndp: 900
    },
    {
        code: '71',
        name: 'PT HAUSJO DIGITAL PRO',
        type_trans: 'Cash Withdrawal',
        acq_fee_atmi: 250,
        acq_fee_ads: 150,
        acq_fee_client: 1500,
        switching_fee_alto: 950,
        recon_fee_alto: 2750,
        beneficiary: 0,
        acq_fee_rts: 650,
        acq_fee_ndp: 1250
    },
    {
        code: '71',
        name: 'PT HAUSJO DIGITAL PRO',
        type_trans: 'Funds Transfer',
        acq_fee_atmi: 250,
        acq_fee_ads: 150,
        acq_fee_client: 1000,
        switching_fee_alto: 1200,
        recon_fee_alto: 900,
        beneficiary: 1500,
        acq_fee_rts: 250,
        acq_fee_ndp: 1250
    },
    {
        code: '71',
        name: 'PT HAUSJO DIGITAL PRO',
        type_trans: 'Balance Inquiry',
        acq_fee_atmi: 200,
        acq_fee_ads: 150,
        acq_fee_client: 1000,
        switching_fee_alto: 750,
        recon_fee_alto: 750,
        beneficiary: 0,
        acq_fee_rts: 250,
        acq_fee_ndp: 900
    },
    {
        code: '73',
        name: 'PT MITRA PEDAGANG INDONESIA',
        type_trans: 'Cash Withdrawal',
        acq_fee_atmi: 250,
        acq_fee_ads: 150,
        acq_fee_client: 1500,
        switching_fee_alto: 950,
        recon_fee_alto: 2750,
        beneficiary: 0,
        acq_fee_rts: 650,
        acq_fee_ndp: 1250
    },
    {
        code: '73',
        name: 'PT MITRA PEDAGANG INDONESIA',
        type_trans: 'Funds Transfer',
        acq_fee_atmi: 250,
        acq_fee_ads: 150,
        acq_fee_client: 1000,
        switching_fee_alto: 1200,
        recon_fee_alto: 900,
        beneficiary: 1500,
        acq_fee_rts: 250,
        acq_fee_ndp: 1250
    },
    {
        code: '73',
        name: 'PT MITRA PEDAGANG INDONESIA',
        type_trans: 'Balance Inquiry',
        acq_fee_atmi: 200,
        acq_fee_ads: 150,
        acq_fee_client: 1000,
        switching_fee_alto: 750,
        recon_fee_alto: 750,
        beneficiary: 0,
        acq_fee_rts: 250,
        acq_fee_ndp: 900
    },
    {
        code: '74',
        name: 'LPD BALI/USSI',
        type_trans: 'Cash Withdrawal',
        acq_fee_atmi: 250,
        acq_fee_ads: 150,
        acq_fee_client: 1500,
        switching_fee_alto: 950,
        recon_fee_alto: 2750,
        beneficiary: 0,
        acq_fee_rts: 650,
        acq_fee_ndp: 1250
    },
    {
        code: '74',
        name: 'LPD BALI/USSI',
        type_trans: 'Funds Transfer',
        acq_fee_atmi: 250,
        acq_fee_ads: 150,
        acq_fee_client: 1000,
        switching_fee_alto: 1200,
        recon_fee_alto: 900,
        beneficiary: 1500,
        acq_fee_rts: 250,
        acq_fee_ndp: 1250
    },
    {
        code: '74',
        name: 'LPD BALI/USSI',
        type_trans: 'Balance Inquiry',
        acq_fee_atmi: 200,
        acq_fee_ads: 150,
        acq_fee_client: 1000,
        switching_fee_alto: 750,
        recon_fee_alto: 750,
        beneficiary: 0,
        acq_fee_rts: 250,
        acq_fee_ndp: 900
    },
    {
        code: '77',
        name: 'YouTap',
        type_trans: 'Cash Withdrawal',
        acq_fee_atmi: 250,
        acq_fee_ads: 0,
        acq_fee_client: 2000,
        switching_fee_alto: 950,
        recon_fee_alto: 2550,
        beneficiary: 0,
        acq_fee_rts: 600,
        acq_fee_ndp: 1150
    },
    {
        code: '77',
        name: 'YouTap',
        type_trans: 'Funds Transfer',
        acq_fee_atmi: 250,
        acq_fee_ads: 0,
        acq_fee_client: 1400,
        switching_fee_alto: 1200,
        recon_fee_alto: 700,
        beneficiary: 1500,
        acq_fee_rts: 300,
        acq_fee_ndp: 1150
    },
    {
        code: '77',
        name: 'YouTap',
        type_trans: 'Balance Inquiry',
        acq_fee_atmi: 200,
        acq_fee_ads: 0,
        acq_fee_client: 1400,
        switching_fee_alto: 750,
        recon_fee_alto: 600,
        beneficiary: 0,
        acq_fee_rts: 250,
        acq_fee_ndp: 800
    },
    {
        code: '78',
        name: 'Parimanta',
        type_trans: 'Cash Withdrawal',
        acq_fee_atmi: 250,
        acq_fee_ads: 0,
        acq_fee_client: 1500,
        switching_fee_alto: 950,
        recon_fee_alto: 2750,
        beneficiary: 0,
        acq_fee_rts: 800,
        acq_fee_ndp: 1250
    },
    {
        code: '78',
        name: 'Parimanta',
        type_trans: 'Funds Transfer',
        acq_fee_atmi: 250,
        acq_fee_ads: 0,
        acq_fee_client: 1000,
        switching_fee_alto: 1200,
        recon_fee_alto: 900,
        beneficiary: 1500,
        acq_fee_rts: 400,
        acq_fee_ndp: 1250
    },
    {
        code: '78',
        name: 'Parimanta',
        type_trans: 'Balance Inquiry',
        acq_fee_atmi: 200,
        acq_fee_ads: 0,
        acq_fee_client: 1000,
        switching_fee_alto: 750,
        recon_fee_alto: 750,
        beneficiary: 0,
        acq_fee_rts: 400,
        acq_fee_ndp: 900
    }
];

module.exports = clientSeeds;